/**
 * `isNetscapeCookieText` 单测(v1.0 Task 3 · `M-015`)。
 *
 * 这条判定的**存在理由**是:第三档选一个 `.jpg` 也照收,用户要等到下载失败、拿到一个指向别处的
 * 错误码才知道选错了(v1.0 Task 2 手测 N08)。故本文件的核心是两组对照 ——
 * **真 cookies.txt 必须被收下**(否则会把好文件挡在门外,比不校验更坏)与
 * **误选的二进制 / 文本必须被认出来**。
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'

import { isNetscapeCookieText } from './cookieFileFormat'

/** Firefox / 常见扩展导出的形态:注释头 + TAB 分隔七字段 */
const REAL = [
  '# Netscape HTTP Cookie File',
  '# This file was generated by a browser extension',
  '',
  '.example.com\tTRUE\t/\tTRUE\t1893456000\tSESSDATA\tabc123',
  '#HttpOnly_.example.com\tTRUE\t/\tTRUE\t1893456000\tbili_jct\tdef456'
].join('\n')

test('M-015 真 cookies.txt(带 Netscape 头)→ 收下', () => {
  assert.equal(isNetscapeCookieText(REAL), true)
})

test('M-015 只有注释头、还没有任何 cookie → 仍收下(空表是合法的空 cookie 文件)', () => {
  assert.equal(isNetscapeCookieText('# Netscape HTTP Cookie File\n'), true)
})

test('M-015 无注释头但有合法数据行 → 收下(不是所有导出工具都写头)', () => {
  assert.equal(
    isNetscapeCookieText('.example.com\tTRUE\t/\tFALSE\t0\tname\tvalue\n'),
    true,
    '缺头不构成拒收理由 —— 把好文件挡在门外比不校验更坏'
  )
})

test('M-015 CRLF 换行 → 收下(Windows 导出的常见形态)', () => {
  assert.equal(isNetscapeCookieText(REAL.replace(/\n/g, '\r\n')), true)
})

test('M-015 误选 .jpg(二进制)→ 认出来', () => {
  // 以 utf-8 读二进制会得到 U+FFFD 替换字符;JPEG 头里还带 NUL
  const jpg = '\uFFFD\uFFFD\uFFFD\uFFFD\0JFIF\0\u0001\uFFFD\uFFFD'
  assert.equal(isNetscapeCookieText(jpg), false)
})

test('M-015 误选普通文本 / JSON → 认出来(纯文本也不是 cookies.txt)', () => {
  assert.equal(isNetscapeCookieText('hello world\n第二行\n'), false)
  assert.equal(isNetscapeCookieText('{"cookies":[{"name":"a","value":"b"}]}'), false)
})

test('M-015 空文件 → 认出来(既无头也无数据行)', () => {
  assert.equal(isNetscapeCookieText(''), false)
  assert.equal(isNetscapeCookieText('\n\n\n'), false)
})

test('M-015 字段够 7 个但不是 TRUE/FALSE 旗标 → 不算(空格分隔的表格会撞上来)', () => {
  assert.equal(isNetscapeCookieText('a\tb\tc\td\te\tf\tg\n'), false)
  assert.equal(isNetscapeCookieText('.example.com TRUE / TRUE 0 name value\n'), false, 'TAB 才算')
})

test('M-015 全是注释行 → 不算(注释里出现七个 TAB 也不该被当成数据)', () => {
  assert.equal(isNetscapeCookieText('# a\tTRUE\t/\tTRUE\t0\tn\tv\n# 另一行\n'), false)
})
